name: Madison Python Users' Group
highlighter: pygments

authors:
  sigmavirus24:
    name: Ian Cordasco

  ceaess:
    name: Cea Stapleton

  olooney:
    name: Oran Looney

  whblondeau:
    name: Bill Blondeau

  # Template:
  # <github_username>:
  #   name: <your_real_name>
