name: Madison Python Users' Group
markdown: redcarpet
pygments: true

authors:
  sigmavirus24:
    name: Ian Cordasco

  olooney:
    name: Oran Looney

  whblondeau:
    name: Bill Blondeau

  # Template:
  # <github_username>:
  #   name: <your_real_name>
